"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#565f89)\
$os\
$hostname\
$username\
[](bg:color_bg3 fg:#565f89)\
$directory\
[](fg:color_bg3 bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'tokyonight'

[palettes.tokyonight]
# 統一冷色調定義
color_fg = '#c0caf5'      # 主要文字色 (冷白)
color_bg = '#1f2335'      # 主背景色 (深藍)
color_bg1 = '#1f2335'     # 時間區塊背景 (最深色)
color_bg3 = '#292e42'     # 區塊分隔背景 (中深色)
color_blue = '#7aa2f7'    # 語言模組背景 (藍色)
color_aqua = '#7dcfff'    # Git 模組背景 (青色)
color_green = '#9ece6a'   # 成功符號 (綠色，仍是冷色系常用色)
color_red = '#f7768e'     # 錯誤符號 (紅色，無法避免)
color_purple = '#bb9af7'  # Vim 模式 (紫色)
# **移除 color_orange 和 color_yellow 鮮豔區塊**

# --- 模組設定：全部統一為冷色調 ---

[os]
disabled = false
# 初始區塊使用柔和的前景色作為背景
style = "bg:#565f89 fg:color_fg" # 使用深灰色 #565f89 作為柔和的起始色

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
# 初始區塊使用柔和的前景色作為背景
style_user = "bg:#565f89 fg:color_fg"
# style_root = "bg:#565f89 fg:color_fg"
style_root = "bg:#565f89 fg:#ff0000"
format = '[$user]($style)'

[hostname]
# 保持與 os/username 相同的樣式
style = "bg:#565f89 fg:color_fg"
# 顯示格式為 [ @hostname ]
format = '[ $hostname/]($style)'
# 只在 SSH 連線時顯示，或設定為 `show_always = true` 讓它總是顯示
ssh_only = false

[directory]
# 目錄背景使用中深色 color_bg3
style = "fg:color_fg bg:color_bg3"
#format = "[ $path ]($style)"
format = "[ $read_only$path ]($style)"
truncate_to_repo = false
#truncation_length = 3
#truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
# Git 模組背景使用 color_aqua (青色)
style = "bg:color_aqua"
# **調整：前景色從 color_fg 改為 color_bg3，讓文字變暗凸顯**
format = '[[ $symbol $branch ](fg:color_bg3 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
# **調整：前景色從 color_fg 改為 color_bg3，讓文字變暗凸顯**
format = '[[($all_status$ahead_behind )](fg:color_bg3 bg:color_aqua)]($style)'

# --- 程式語言模組 (統一使用 color_blue) ---
[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_blue)]($style)'

# --- 環境/上下文模組 (統一使用 color_bg3) ---
[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_fg bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_fg bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
# 使用 color_aqua 作為視覺模式的顏色
vimcmd_visual_symbol = '[](bold fg:color_aqua)'
